version: "3.1"

services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        volumes:
            - ./mariadb:/var/lib/mysql
        environment:
            - MARIADB_ROOT_PASSWORD=password
            - MARIADB_DATABASE=api
            - MARIADB_USER=qpro
            - MARIADB_PASSWORD=qpro
        ports:
            - 3306:3306